name: Platform setup
description: Install Freckle Platform CLI
inputs:
  version:
    description: Version of Platform CLI to install
    required: true
    default: ""
  suffix:
    description: OS-specific suffix for Platform package archive
    required: true
    default: x86_64-linux
  token:
    description: GitHub Token with access to freckle/platform repository
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - uses: robinraju/release-downloader@v1.3
      with:
        repository: freckle/platform
        latest: ${{ inputs.version == '' }}
        tag: ${{ inputs.version }}
        fileName: platform-${{ inputs.suffix }}.tar.gz
        token: ${{ inputs.token }}

    - shell: bash
      run: tar xzvf ./platform-${{ inputs.suffix }}.tar.gz

    - shell: bash
      run: cd ./platform && sudo make install

    - id: setup
      shell: bash
      run: |
        case "${{ inputs.version }}" in
          v0* | v1* | v2.0*)
            echo "::set-output name=needs-cfn-flip::true"
            ;;
          *)
            echo "::set-output name=needs-cfn-flip::false"
            ;;
        esac

    - if: ${{ steps.setup.outputs.needs-cfn-flip == 'true' }}
      uses: actions/setup-python@v2

    - if: ${{ steps.setup.outputs.needs-cfn-flip == 'true' }}
      shell: bash
      run: pip install cfn-flip
