name: Platform setup
description: Install Freckle Platform CLI
inputs:
  version:
    description: Version of Platform CLI to install
    required: true
    default: ""
  suffix:
    description: OS-specific suffix for Platform package archive
    required: true
    default: x86_64-linux
  token:
    description: GitHub Token with access to freckle/platform repository
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Download
      uses: robinraju/release-downloader@v1.3
      with:
        repository: freckle/platform
        latest: ${{ inputs.version == '' }}
        tag: ${{ inputs.version }}
        fileName: platform-${{ inputs.suffix }}.tar.gz
        token: ${{ inputs.token }}

    - shell: bash
      name: Extract
      run: tar xzvf ./platform-${{ inputs.suffix }}.tar.gz

    - shell: bash
      name: Install
      run: cd ./platform && sudo make install
