name: Platform setup
description: Install Freckle Platform CLI
inputs:
  version:
    description: Version of Platform CLI to install
    required: true
    default: latest
  suffix:
    description: OS-specific suffix for Platform package archive
    require: true
    default: x86_64-linux
outputs: {}
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        ${{ github.action_path }}/bin/install \
          -v "${{ inputs.version }}" \
          -s "${{ inputs.suffix }}" \
          -S
