name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
      - run: platform version
      - run: stackctl version

  test-defaults:
    strategy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: setup
        uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0
      - uses: brokenpip3/setup-bats-libs@0.1.0
      - run: test/defaults.bats
        env:
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GH_PUSH_SHA: ${{ github.event.push.after }}
          GH_SHA: ${{ github.sha }}
          TAG: ${{ steps.setup.outputs.tag }}

  test-configured:
    runs-on: ubuntu-latest
    env:
      # Dummy env so the older CLI versions don't fail on initialization. Once a
      # non-latest version has that fix, we can update here and remove this.
      AWS_ACCESS_KEY_ID: x
      AWS_SECRET_ACCESS_KEY: x

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
          version: "2.1.0.0"
          environment: dev
          app: my-app
          resource: my-resource
          no-validate: "1"
          stackctl-version: "1.1.4.0"
      - uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0
      - uses: brokenpip3/setup-bats-libs@0.1.0
      - run: test/configured.bats
        env:
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GH_PUSH_SHA: ${{ github.event.push.after }}
          GH_SHA: ${{ github.sha }}
          TAG: ${{ steps.setup.outputs.tag }}
