name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - macOS-latest
      fail-fast: false
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
      - run: platform version
      - run: stackctl version

  test-defaults:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: rm .platform.yaml # so it'll be downloaded
      - id: setup
        uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
      - uses: bats-core/bats-action@2.0.0
        with:
          support-path: /usr/lib/bats/bats-support
          assert-path: /usr/lib/bats/bats-assert
      - run: bats test/defaults.bats
        env:
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GH_PUSH_SHA: ${{ github.event.after }}
          GH_SHA: ${{ github.sha }}
          TAG: ${{ steps.setup.outputs.tag }}

  test-configured:
    runs-on: ubuntu-latest
    env:
      # Dummy env so the older CLI versions don't fail on initialization. Once a
      # non-latest version has that fix, we can update here and remove this.
      AWS_ACCESS_KEY_ID: x
      AWS_SECRET_ACCESS_KEY: x

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.FRECKLE_AUTOMATION_GITHUB_TOKEN }}
          version: "2.1.0.0"
          app-directory: my-app
          environment: dev
          resource: my-resource
          no-validate: "1"
          stackctl-version: "1.4.0.0"
          fetch-platform-yaml: false
      - uses: bats-core/bats-action@2.0.0
        with:
          support-path: /usr/lib/bats/bats-support
          assert-path: /usr/lib/bats/bats-assert
      - run: bats test/defaults.bats
      - run: bats test/configured.bats
        env:
          GH_EVENT_NAME: ${{ github.event_name }}
          GH_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GH_PUSH_SHA: ${{ github.event.push.after }}
          GH_SHA: ${{ github.sha }}
          TAG: ${{ steps.setup.outputs.tag }}
